// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static EasyBot.Controllers.AccountController Account = new EasyBot.Controllers.T4MVC_AccountController();
    public static EasyBot.Controllers.AdminController Admin = new EasyBot.Controllers.T4MVC_AdminController();
    public static EasyBot.Controllers.BaseController Base = new EasyBot.Controllers.T4MVC_BaseController();
    public static EasyBot.Controllers.ChartController Chart = new EasyBot.Controllers.T4MVC_ChartController();
    public static EasyBot.Controllers.HomeController Home = new EasyBot.Controllers.T4MVC_HomeController();
    public static EasyBot.Controllers.InstrumentController Instrument = new EasyBot.Controllers.T4MVC_InstrumentController();
    public static EasyBot.Controllers.ManageController Manage = new EasyBot.Controllers.T4MVC_ManageController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_EmptyResult : System.Web.Mvc.EmptyResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_EmptyResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class chart {
            private const string URLPATH = "~/Scripts/chart";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string chart_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/chart.min.js") ? Url("chart.min.js") : Url("chart.js");
        }
    
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
        public static readonly string jquery_jqGrid_min_js = Url("jquery.jqGrid.min.js");
        public static readonly string jquery_signalR_2_2_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.signalR-2.2.0.min.js") ? Url("jquery.signalR-2.2.0.min.js") : Url("jquery.signalR-2.2.0.js");
        public static readonly string jquery_signalR_2_2_0_min_js = Url("jquery.signalR-2.2.0.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string knockout_3_4_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-3.4.0.min.js") ? Url("knockout-3.4.0.min.js") : Url("knockout-3.4.0.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class locale {
            private const string URLPATH = "~/Scripts/locale";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string grid_locale_en_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-en.min.js") ? Url("grid.locale-en.min.js") : Url("grid.locale-en.js");
            public static readonly string grid_locale_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ru.min.js") ? Url("grid.locale-ru.min.js") : Url("grid.locale-ru.js");
        }
    
        public static readonly string main_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/main.min.js") ? Url("main.min.js") : Url("main.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class streaming {
            private const string URLPATH = "~/Scripts/streaming";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string signalR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/signalR.min.js") ? Url("signalR.min.js") : Url("signalR.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class vendors {
            private const string URLPATH = "~/Scripts/vendors";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class zingchart {
                private const string URLPATH = "~/Scripts/vendors/zingchart";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class modules {
                    private const string URLPATH = "~/Scripts/vendors/zingchart/modules";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string zingchart_3d_min_js = Url("zingchart-3d.min.js");
                    public static readonly string zingchart_animation_min_js = Url("zingchart-animation.min.js");
                    public static readonly string zingchart_api_annotations_min_js = Url("zingchart-api-annotations.min.js");
                    public static readonly string zingchart_api_rules_min_js = Url("zingchart-api-rules.min.js");
                    public static readonly string zingchart_api_min_js = Url("zingchart-api.min.js");
                    public static readonly string zingchart_area_min_js = Url("zingchart-area.min.js");
                    public static readonly string zingchart_area3d_min_js = Url("zingchart-area3d.min.js");
                    public static readonly string zingchart_boxplot_min_js = Url("zingchart-boxplot.min.js");
                    public static readonly string zingchart_bubble_min_js = Url("zingchart-bubble.min.js");
                    public static readonly string zingchart_bubblepie_min_js = Url("zingchart-bubblepie.min.js");
                    public static readonly string zingchart_calendar_min_js = Url("zingchart-calendar.min.js");
                    public static readonly string zingchart_chord_min_js = Url("zingchart-chord.min.js");
                    public static readonly string zingchart_core_min_js = Url("zingchart-core.min.js");
                    public static readonly string zingchart_csv_min_js = Url("zingchart-csv.min.js");
                    public static readonly string zingchart_debug_min_js = Url("zingchart-debug.min.js");
                    public static readonly string zingchart_dragging_min_js = Url("zingchart-dragging.min.js");
                    public static readonly string zingchart_errorbars_min_js = Url("zingchart-errorbars.min.js");
                    public static readonly string zingchart_export_min_js = Url("zingchart-export.min.js");
                    public static readonly string zingchart_gauge_min_js = Url("zingchart-gauge.min.js");
                    public static readonly string zingchart_grid_min_js = Url("zingchart-grid.min.js");
                    public static readonly string zingchart_guide_min_js = Url("zingchart-guide.min.js");
                    public static readonly string zingchart_hbar_min_js = Url("zingchart-hbar.min.js");
                    public static readonly string zingchart_hbar3d_min_js = Url("zingchart-hbar3d.min.js");
                    public static readonly string zingchart_hbubble_min_js = Url("zingchart-hbubble.min.js");
                    public static readonly string zingchart_hbullet_min_js = Url("zingchart-hbullet.min.js");
                    public static readonly string zingchart_hfunnel_min_js = Url("zingchart-hfunnel.min.js");
                    public static readonly string zingchart_history_min_js = Url("zingchart-history.min.js");
                    public static readonly string zingchart_hscatter_min_js = Url("zingchart-hscatter.min.js");
                    public static readonly string zingchart_legend_min_js = Url("zingchart-legend.min.js");
                    public static readonly string zingchart_line_min_js = Url("zingchart-line.min.js");
                    public static readonly string zingchart_line3d_min_js = Url("zingchart-line3d.min.js");
                    public static readonly string zingchart_maps_afg_min_js = Url("zingchart-maps-afg.min.js");
                    public static readonly string zingchart_maps_ago_min_js = Url("zingchart-maps-ago.min.js");
                    public static readonly string zingchart_maps_alb_min_js = Url("zingchart-maps-alb.min.js");
                    public static readonly string zingchart_maps_and_min_js = Url("zingchart-maps-and.min.js");
                    public static readonly string zingchart_maps_are_min_js = Url("zingchart-maps-are.min.js");
                    public static readonly string zingchart_maps_arg_min_js = Url("zingchart-maps-arg.min.js");
                    public static readonly string zingchart_maps_arm_min_js = Url("zingchart-maps-arm.min.js");
                    public static readonly string zingchart_maps_aus_min_js = Url("zingchart-maps-aus.min.js");
                    public static readonly string zingchart_maps_aut_min_js = Url("zingchart-maps-aut.min.js");
                    public static readonly string zingchart_maps_aze_min_js = Url("zingchart-maps-aze.min.js");
                    public static readonly string zingchart_maps_bdi_min_js = Url("zingchart-maps-bdi.min.js");
                    public static readonly string zingchart_maps_bel_min_js = Url("zingchart-maps-bel.min.js");
                    public static readonly string zingchart_maps_ben_min_js = Url("zingchart-maps-ben.min.js");
                    public static readonly string zingchart_maps_bfa_min_js = Url("zingchart-maps-bfa.min.js");
                    public static readonly string zingchart_maps_bgr_min_js = Url("zingchart-maps-bgr.min.js");
                    public static readonly string zingchart_maps_bih_min_js = Url("zingchart-maps-bih.min.js");
                    public static readonly string zingchart_maps_blr_min_js = Url("zingchart-maps-blr.min.js");
                    public static readonly string zingchart_maps_bol_min_js = Url("zingchart-maps-bol.min.js");
                    public static readonly string zingchart_maps_bra_min_js = Url("zingchart-maps-bra.min.js");
                    public static readonly string zingchart_maps_brn_min_js = Url("zingchart-maps-brn.min.js");
                    public static readonly string zingchart_maps_btn_min_js = Url("zingchart-maps-btn.min.js");
                    public static readonly string zingchart_maps_bwa_min_js = Url("zingchart-maps-bwa.min.js");
                    public static readonly string zingchart_maps_caf_min_js = Url("zingchart-maps-caf.min.js");
                    public static readonly string zingchart_maps_can_min_js = Url("zingchart-maps-can.min.js");
                    public static readonly string zingchart_maps_che_min_js = Url("zingchart-maps-che.min.js");
                    public static readonly string zingchart_maps_chl_min_js = Url("zingchart-maps-chl.min.js");
                    public static readonly string zingchart_maps_chn_min_js = Url("zingchart-maps-chn.min.js");
                    public static readonly string zingchart_maps_civ_min_js = Url("zingchart-maps-civ.min.js");
                    public static readonly string zingchart_maps_cmr_min_js = Url("zingchart-maps-cmr.min.js");
                    public static readonly string zingchart_maps_cod_min_js = Url("zingchart-maps-cod.min.js");
                    public static readonly string zingchart_maps_cog_min_js = Url("zingchart-maps-cog.min.js");
                    public static readonly string zingchart_maps_col_min_js = Url("zingchart-maps-col.min.js");
                    public static readonly string zingchart_maps_cri_min_js = Url("zingchart-maps-cri.min.js");
                    public static readonly string zingchart_maps_cub_min_js = Url("zingchart-maps-cub.min.js");
                    public static readonly string zingchart_maps_cyp_min_js = Url("zingchart-maps-cyp.min.js");
                    public static readonly string zingchart_maps_cze_min_js = Url("zingchart-maps-cze.min.js");
                    public static readonly string zingchart_maps_deu_min_js = Url("zingchart-maps-deu.min.js");
                    public static readonly string zingchart_maps_dnk_min_js = Url("zingchart-maps-dnk.min.js");
                    public static readonly string zingchart_maps_ecu_min_js = Url("zingchart-maps-ecu.min.js");
                    public static readonly string zingchart_maps_egy_min_js = Url("zingchart-maps-egy.min.js");
                    public static readonly string zingchart_maps_esp_min_js = Url("zingchart-maps-esp.min.js");
                    public static readonly string zingchart_maps_espL2_min_js = Url("zingchart-maps-espL2.min.js");
                    public static readonly string zingchart_maps_est_min_js = Url("zingchart-maps-est.min.js");
                    public static readonly string zingchart_maps_eth_min_js = Url("zingchart-maps-eth.min.js");
                    public static readonly string zingchart_maps_fin_min_js = Url("zingchart-maps-fin.min.js");
                    public static readonly string zingchart_maps_fra_min_js = Url("zingchart-maps-fra.min.js");
                    public static readonly string zingchart_maps_fraL2_min_js = Url("zingchart-maps-fraL2.min.js");
                    public static readonly string zingchart_maps_gab_min_js = Url("zingchart-maps-gab.min.js");
                    public static readonly string zingchart_maps_gbr_min_js = Url("zingchart-maps-gbr.min.js");
                    public static readonly string zingchart_maps_gbrL2_min_js = Url("zingchart-maps-gbrL2.min.js");
                    public static readonly string zingchart_maps_geojson_min_js = Url("zingchart-maps-geojson.min.js");
                    public static readonly string zingchart_maps_gha_min_js = Url("zingchart-maps-gha.min.js");
                    public static readonly string zingchart_maps_gmb_min_js = Url("zingchart-maps-gmb.min.js");
                    public static readonly string zingchart_maps_gnb_min_js = Url("zingchart-maps-gnb.min.js");
                    public static readonly string zingchart_maps_grc_min_js = Url("zingchart-maps-grc.min.js");
                    public static readonly string zingchart_maps_gtm_min_js = Url("zingchart-maps-gtm.min.js");
                    public static readonly string zingchart_maps_guf_min_js = Url("zingchart-maps-guf.min.js");
                    public static readonly string zingchart_maps_guy_min_js = Url("zingchart-maps-guy.min.js");
                    public static readonly string zingchart_maps_hrv_min_js = Url("zingchart-maps-hrv.min.js");
                    public static readonly string zingchart_maps_hun_min_js = Url("zingchart-maps-hun.min.js");
                    public static readonly string zingchart_maps_ind_min_js = Url("zingchart-maps-ind.min.js");
                    public static readonly string zingchart_maps_irl_min_js = Url("zingchart-maps-irl.min.js");
                    public static readonly string zingchart_maps_irn_min_js = Url("zingchart-maps-irn.min.js");
                    public static readonly string zingchart_maps_isl_min_js = Url("zingchart-maps-isl.min.js");
                    public static readonly string zingchart_maps_isr_min_js = Url("zingchart-maps-isr.min.js");
                    public static readonly string zingchart_maps_ita_min_js = Url("zingchart-maps-ita.min.js");
                    public static readonly string zingchart_maps_jpn_min_js = Url("zingchart-maps-jpn.min.js");
                    public static readonly string zingchart_maps_kaz_min_js = Url("zingchart-maps-kaz.min.js");
                    public static readonly string zingchart_maps_ken_min_js = Url("zingchart-maps-ken.min.js");
                    public static readonly string zingchart_maps_kor_min_js = Url("zingchart-maps-kor.min.js");
                    public static readonly string zingchart_maps_kwt_min_js = Url("zingchart-maps-kwt.min.js");
                    public static readonly string zingchart_maps_lao_min_js = Url("zingchart-maps-lao.min.js");
                    public static readonly string zingchart_maps_lbr_min_js = Url("zingchart-maps-lbr.min.js");
                    public static readonly string zingchart_maps_lie_min_js = Url("zingchart-maps-lie.min.js");
                    public static readonly string zingchart_maps_ltu_min_js = Url("zingchart-maps-ltu.min.js");
                    public static readonly string zingchart_maps_lux_min_js = Url("zingchart-maps-lux.min.js");
                    public static readonly string zingchart_maps_lva_min_js = Url("zingchart-maps-lva.min.js");
                    public static readonly string zingchart_maps_mda_min_js = Url("zingchart-maps-mda.min.js");
                    public static readonly string zingchart_maps_mex_min_js = Url("zingchart-maps-mex.min.js");
                    public static readonly string zingchart_maps_mkd_min_js = Url("zingchart-maps-mkd.min.js");
                    public static readonly string zingchart_maps_mne_min_js = Url("zingchart-maps-mne.min.js");
                    public static readonly string zingchart_maps_moz_min_js = Url("zingchart-maps-moz.min.js");
                    public static readonly string zingchart_maps_nam_min_js = Url("zingchart-maps-nam.min.js");
                    public static readonly string zingchart_maps_ncl_min_js = Url("zingchart-maps-ncl.min.js");
                    public static readonly string zingchart_maps_nga_min_js = Url("zingchart-maps-nga.min.js");
                    public static readonly string zingchart_maps_nld_min_js = Url("zingchart-maps-nld.min.js");
                    public static readonly string zingchart_maps_nor_min_js = Url("zingchart-maps-nor.min.js");
                    public static readonly string zingchart_maps_nzl_min_js = Url("zingchart-maps-nzl.min.js");
                    public static readonly string zingchart_maps_omn_min_js = Url("zingchart-maps-omn.min.js");
                    public static readonly string zingchart_maps_pak_min_js = Url("zingchart-maps-pak.min.js");
                    public static readonly string zingchart_maps_pan_min_js = Url("zingchart-maps-pan.min.js");
                    public static readonly string zingchart_maps_per_min_js = Url("zingchart-maps-per.min.js");
                    public static readonly string zingchart_maps_phl_min_js = Url("zingchart-maps-phl.min.js");
                    public static readonly string zingchart_maps_png_min_js = Url("zingchart-maps-png.min.js");
                    public static readonly string zingchart_maps_pol_min_js = Url("zingchart-maps-pol.min.js");
                    public static readonly string zingchart_maps_prt_min_js = Url("zingchart-maps-prt.min.js");
                    public static readonly string zingchart_maps_qat_min_js = Url("zingchart-maps-qat.min.js");
                    public static readonly string zingchart_maps_rou_min_js = Url("zingchart-maps-rou.min.js");
                    public static readonly string zingchart_maps_rus_min_js = Url("zingchart-maps-rus.min.js");
                    public static readonly string zingchart_maps_rwa_min_js = Url("zingchart-maps-rwa.min.js");
                    public static readonly string zingchart_maps_sen_min_js = Url("zingchart-maps-sen.min.js");
                    public static readonly string zingchart_maps_slv_min_js = Url("zingchart-maps-slv.min.js");
                    public static readonly string zingchart_maps_srb_min_js = Url("zingchart-maps-srb.min.js");
                    public static readonly string zingchart_maps_sur_min_js = Url("zingchart-maps-sur.min.js");
                    public static readonly string zingchart_maps_svk_min_js = Url("zingchart-maps-svk.min.js");
                    public static readonly string zingchart_maps_svn_min_js = Url("zingchart-maps-svn.min.js");
                    public static readonly string zingchart_maps_swe_min_js = Url("zingchart-maps-swe.min.js");
                    public static readonly string zingchart_maps_tha_min_js = Url("zingchart-maps-tha.min.js");
                    public static readonly string zingchart_maps_tjk_min_js = Url("zingchart-maps-tjk.min.js");
                    public static readonly string zingchart_maps_topojson_min_js = Url("zingchart-maps-topojson.min.js");
                    public static readonly string zingchart_maps_tun_min_js = Url("zingchart-maps-tun.min.js");
                    public static readonly string zingchart_maps_tur_min_js = Url("zingchart-maps-tur.min.js");
                    public static readonly string zingchart_maps_twn_min_js = Url("zingchart-maps-twn.min.js");
                    public static readonly string zingchart_maps_uga_min_js = Url("zingchart-maps-uga.min.js");
                    public static readonly string zingchart_maps_ukr_min_js = Url("zingchart-maps-ukr.min.js");
                    public static readonly string zingchart_maps_ury_min_js = Url("zingchart-maps-ury.min.js");
                    public static readonly string zingchart_maps_usa_min_js = Url("zingchart-maps-usa.min.js");
                    public static readonly string zingchart_maps_usa_ak_min_js = Url("zingchart-maps-usa_ak.min.js");
                    public static readonly string zingchart_maps_usa_al_min_js = Url("zingchart-maps-usa_al.min.js");
                    public static readonly string zingchart_maps_usa_ar_min_js = Url("zingchart-maps-usa_ar.min.js");
                    public static readonly string zingchart_maps_usa_az_min_js = Url("zingchart-maps-usa_az.min.js");
                    public static readonly string zingchart_maps_usa_ca_min_js = Url("zingchart-maps-usa_ca.min.js");
                    public static readonly string zingchart_maps_usa_co_min_js = Url("zingchart-maps-usa_co.min.js");
                    public static readonly string zingchart_maps_usa_ct_min_js = Url("zingchart-maps-usa_ct.min.js");
                    public static readonly string zingchart_maps_usa_dc_min_js = Url("zingchart-maps-usa_dc.min.js");
                    public static readonly string zingchart_maps_usa_de_min_js = Url("zingchart-maps-usa_de.min.js");
                    public static readonly string zingchart_maps_usa_fl_min_js = Url("zingchart-maps-usa_fl.min.js");
                    public static readonly string zingchart_maps_usa_ga_min_js = Url("zingchart-maps-usa_ga.min.js");
                    public static readonly string zingchart_maps_usa_hi_min_js = Url("zingchart-maps-usa_hi.min.js");
                    public static readonly string zingchart_maps_usa_ia_min_js = Url("zingchart-maps-usa_ia.min.js");
                    public static readonly string zingchart_maps_usa_id_min_js = Url("zingchart-maps-usa_id.min.js");
                    public static readonly string zingchart_maps_usa_il_min_js = Url("zingchart-maps-usa_il.min.js");
                    public static readonly string zingchart_maps_usa_in_min_js = Url("zingchart-maps-usa_in.min.js");
                    public static readonly string zingchart_maps_usa_ks_min_js = Url("zingchart-maps-usa_ks.min.js");
                    public static readonly string zingchart_maps_usa_ky_min_js = Url("zingchart-maps-usa_ky.min.js");
                    public static readonly string zingchart_maps_usa_la_min_js = Url("zingchart-maps-usa_la.min.js");
                    public static readonly string zingchart_maps_usa_ma_min_js = Url("zingchart-maps-usa_ma.min.js");
                    public static readonly string zingchart_maps_usa_md_min_js = Url("zingchart-maps-usa_md.min.js");
                    public static readonly string zingchart_maps_usa_me_min_js = Url("zingchart-maps-usa_me.min.js");
                    public static readonly string zingchart_maps_usa_mi_min_js = Url("zingchart-maps-usa_mi.min.js");
                    public static readonly string zingchart_maps_usa_mn_min_js = Url("zingchart-maps-usa_mn.min.js");
                    public static readonly string zingchart_maps_usa_mo_min_js = Url("zingchart-maps-usa_mo.min.js");
                    public static readonly string zingchart_maps_usa_ms_min_js = Url("zingchart-maps-usa_ms.min.js");
                    public static readonly string zingchart_maps_usa_mt_min_js = Url("zingchart-maps-usa_mt.min.js");
                    public static readonly string zingchart_maps_usa_nc_min_js = Url("zingchart-maps-usa_nc.min.js");
                    public static readonly string zingchart_maps_usa_nd_min_js = Url("zingchart-maps-usa_nd.min.js");
                    public static readonly string zingchart_maps_usa_ne_min_js = Url("zingchart-maps-usa_ne.min.js");
                    public static readonly string zingchart_maps_usa_nh_min_js = Url("zingchart-maps-usa_nh.min.js");
                    public static readonly string zingchart_maps_usa_nj_min_js = Url("zingchart-maps-usa_nj.min.js");
                    public static readonly string zingchart_maps_usa_nm_min_js = Url("zingchart-maps-usa_nm.min.js");
                    public static readonly string zingchart_maps_usa_nv_min_js = Url("zingchart-maps-usa_nv.min.js");
                    public static readonly string zingchart_maps_usa_ny_min_js = Url("zingchart-maps-usa_ny.min.js");
                    public static readonly string zingchart_maps_usa_oh_min_js = Url("zingchart-maps-usa_oh.min.js");
                    public static readonly string zingchart_maps_usa_ok_min_js = Url("zingchart-maps-usa_ok.min.js");
                    public static readonly string zingchart_maps_usa_or_min_js = Url("zingchart-maps-usa_or.min.js");
                    public static readonly string zingchart_maps_usa_pa_min_js = Url("zingchart-maps-usa_pa.min.js");
                    public static readonly string zingchart_maps_usa_ri_min_js = Url("zingchart-maps-usa_ri.min.js");
                    public static readonly string zingchart_maps_usa_sc_min_js = Url("zingchart-maps-usa_sc.min.js");
                    public static readonly string zingchart_maps_usa_sd_min_js = Url("zingchart-maps-usa_sd.min.js");
                    public static readonly string zingchart_maps_usa_tn_min_js = Url("zingchart-maps-usa_tn.min.js");
                    public static readonly string zingchart_maps_usa_tx_min_js = Url("zingchart-maps-usa_tx.min.js");
                    public static readonly string zingchart_maps_usa_ut_min_js = Url("zingchart-maps-usa_ut.min.js");
                    public static readonly string zingchart_maps_usa_va_min_js = Url("zingchart-maps-usa_va.min.js");
                    public static readonly string zingchart_maps_usa_vt_min_js = Url("zingchart-maps-usa_vt.min.js");
                    public static readonly string zingchart_maps_usa_wa_min_js = Url("zingchart-maps-usa_wa.min.js");
                    public static readonly string zingchart_maps_usa_wi_min_js = Url("zingchart-maps-usa_wi.min.js");
                    public static readonly string zingchart_maps_usa_wv_min_js = Url("zingchart-maps-usa_wv.min.js");
                    public static readonly string zingchart_maps_usa_wy_min_js = Url("zingchart-maps-usa_wy.min.js");
                    public static readonly string zingchart_maps_uzb_min_js = Url("zingchart-maps-uzb.min.js");
                    public static readonly string zingchart_maps_ven_min_js = Url("zingchart-maps-ven.min.js");
                    public static readonly string zingchart_maps_vnm_min_js = Url("zingchart-maps-vnm.min.js");
                    public static readonly string zingchart_maps_world_continents_min_js = Url("zingchart-maps-world-continents.min.js");
                    public static readonly string zingchart_maps_world_countries_min_js = Url("zingchart-maps-world-countries.min.js");
                    public static readonly string zingchart_maps_yem_min_js = Url("zingchart-maps-yem.min.js");
                    public static readonly string zingchart_maps_zaf_min_js = Url("zingchart-maps-zaf.min.js");
                    public static readonly string zingchart_maps_zmb_min_js = Url("zingchart-maps-zmb.min.js");
                    public static readonly string zingchart_maps_zwe_min_js = Url("zingchart-maps-zwe.min.js");
                    public static readonly string zingchart_maps_min_js = Url("zingchart-maps.min.js");
                    public static readonly string zingchart_navpie_min_js = Url("zingchart-navpie.min.js");
                    public static readonly string zingchart_nestedpie_min_js = Url("zingchart-nestedpie.min.js");
                    public static readonly string zingchart_objects_min_js = Url("zingchart-objects.min.js");
                    public static readonly string zingchart_pareto_min_js = Url("zingchart-pareto.min.js");
                    public static readonly string zingchart_patterns_min_js = Url("zingchart-patterns.min.js");
                    public static readonly string zingchart_piano_min_js = Url("zingchart-piano.min.js");
                    public static readonly string zingchart_pie_min_js = Url("zingchart-pie.min.js");
                    public static readonly string zingchart_pie3d_min_js = Url("zingchart-pie3d.min.js");
                    public static readonly string zingchart_populationpyramid_min_js = Url("zingchart-populationpyramid.min.js");
                    public static readonly string zingchart_preview_min_js = Url("zingchart-preview.min.js");
                    public static readonly string zingchart_r_min_js = Url("zingchart-r.min.js");
                    public static readonly string zingchart_radar_min_js = Url("zingchart-radar.min.js");
                    public static readonly string zingchart_range_min_js = Url("zingchart-range.min.js");
                    public static readonly string zingchart_rankflow_min_js = Url("zingchart-rankflow.min.js");
                    public static readonly string zingchart_refresh_min_js = Url("zingchart-refresh.min.js");
                    public static readonly string zingchart_scalemarkers_min_js = Url("zingchart-scalemarkers.min.js");
                    public static readonly string zingchart_scatter_min_js = Url("zingchart-scatter.min.js");
                    public static readonly string zingchart_scroll_min_js = Url("zingchart-scroll.min.js");
                    public static readonly string zingchart_selection_min_js = Url("zingchart-selection.min.js");
                    public static readonly string zingchart_stock_min_js = Url("zingchart-stock.min.js");
                    public static readonly string zingchart_toolbar3d_min_js = Url("zingchart-toolbar3d.min.js");
                    public static readonly string zingchart_tooltip_min_js = Url("zingchart-tooltip.min.js");
                    public static readonly string zingchart_treemap_min_js = Url("zingchart-treemap.min.js");
                    public static readonly string zingchart_varea_min_js = Url("zingchart-varea.min.js");
                    public static readonly string zingchart_vbar_min_js = Url("zingchart-vbar.min.js");
                    public static readonly string zingchart_vbar3d_min_js = Url("zingchart-vbar3d.min.js");
                    public static readonly string zingchart_vbullet_min_js = Url("zingchart-vbullet.min.js");
                    public static readonly string zingchart_venn_min_js = Url("zingchart-venn.min.js");
                    public static readonly string zingchart_vfunnel_min_js = Url("zingchart-vfunnel.min.js");
                    public static readonly string zingchart_vline_min_js = Url("zingchart-vline.min.js");
                    public static readonly string zingchart_waterfall_min_js = Url("zingchart-waterfall.min.js");
                    public static readonly string zingchart_wordcloud_min_js = Url("zingchart-wordcloud.min.js");
                    public static readonly string zingchart_xy_min_js = Url("zingchart-xy.min.js");
                    public static readonly string zingchart_yx_min_js = Url("zingchart-yx.min.js");
                    public static readonly string zingchart_zoom_min_js = Url("zingchart-zoom.min.js");
                }
            
                public static readonly string zingchart_min_js = Url("zingchart.min.js");
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string chart_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/chart.min.css") ? Url("chart.min.css") : Url("chart.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string animated_overlay_gif = Url("animated-overlay.gif");
            public static readonly string code_png = Url("code.png");
            public static readonly string php_png = Url("php.png");
            public static readonly string ui_bg_flat_55_999999_40x100_png = Url("ui-bg_flat_55_999999_40x100.png");
            public static readonly string ui_bg_flat_75_aaaaaa_40x100_png = Url("ui-bg_flat_75_aaaaaa_40x100.png");
            public static readonly string ui_bg_glass_45_0078ae_1x400_png = Url("ui-bg_glass_45_0078ae_1x400.png");
            public static readonly string ui_bg_glass_55_f8da4e_1x400_png = Url("ui-bg_glass_55_f8da4e_1x400.png");
            public static readonly string ui_bg_glass_75_79c9ec_1x400_png = Url("ui-bg_glass_75_79c9ec_1x400.png");
            public static readonly string ui_bg_gloss_wave_45_e14f1c_500x100_png = Url("ui-bg_gloss-wave_45_e14f1c_500x100.png");
            public static readonly string ui_bg_gloss_wave_50_6eac2c_500x100_png = Url("ui-bg_gloss-wave_50_6eac2c_500x100.png");
            public static readonly string ui_bg_gloss_wave_75_2191c0_500x100_png = Url("ui-bg_gloss-wave_75_2191c0_500x100.png");
            public static readonly string ui_bg_inset_hard_100_fcfdfd_1x100_png = Url("ui-bg_inset-hard_100_fcfdfd_1x100.png");
            public static readonly string ui_icons_0078ae_256x240_png = Url("ui-icons_0078ae_256x240.png");
            public static readonly string ui_icons_056b93_256x240_png = Url("ui-icons_056b93_256x240.png");
            public static readonly string ui_icons_444444_256x240_png = Url("ui-icons_444444_256x240.png");
            public static readonly string ui_icons_555555_256x240_png = Url("ui-icons_555555_256x240.png");
            public static readonly string ui_icons_777620_256x240_png = Url("ui-icons_777620_256x240.png");
            public static readonly string ui_icons_777777_256x240_png = Url("ui-icons_777777_256x240.png");
            public static readonly string ui_icons_cc0000_256x240_png = Url("ui-icons_cc0000_256x240.png");
            public static readonly string ui_icons_d8e7f3_256x240_png = Url("ui-icons_d8e7f3_256x240.png");
            public static readonly string ui_icons_e0fdff_256x240_png = Url("ui-icons_e0fdff_256x240.png");
            public static readonly string ui_icons_f5e175_256x240_png = Url("ui-icons_f5e175_256x240.png");
            public static readonly string ui_icons_f7a50d_256x240_png = Url("ui-icons_f7a50d_256x240.png");
            public static readonly string ui_icons_fcd113_256x240_png = Url("ui-icons_fcd113_256x240.png");
            public static readonly string ui_icons_ffffff_256x240_png = Url("ui-icons_ffffff_256x240.png");
        }
    
        public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class rickshaw {
            private const string URLPATH = "~/Content/rickshaw";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string detail_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/detail.min.css") ? Url("detail.min.css") : Url("detail.css");
            public static readonly string graph_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/graph.min.css") ? Url("graph.min.css") : Url("graph.css");
            public static readonly string lines_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/lines.min.css") ? Url("lines.min.css") : Url("lines.css");
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        public static readonly string ui_jqgrid_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui.jqgrid.min.css") ? Url("ui.jqgrid.min.css") : Url("ui.jqgrid.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class chart 
            {
                public static class Assets
                {
                    public const string chart_js = "~/Scripts/chart/chart.js"; 
                }
            }
            public static partial class locale 
            {
                public static class Assets
                {
                    public const string grid_locale_en_js = "~/Scripts/locale/grid.locale-en.js"; 
                    public const string grid_locale_ru_js = "~/Scripts/locale/grid.locale-ru.js"; 
                }
            }
            public static partial class streaming 
            {
                public static class Assets
                {
                    public const string signalR_js = "~/Scripts/streaming/signalR.js"; 
                }
            }
            public static partial class vendors 
            {
                public static partial class zingchart 
                {
                    public static partial class modules 
                    {
                        public static class Assets
                        {
                            public const string zingchart_3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-3d.min.js"; 
                            public const string zingchart_animation_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-animation.min.js"; 
                            public const string zingchart_api_annotations_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-api-annotations.min.js"; 
                            public const string zingchart_api_rules_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-api-rules.min.js"; 
                            public const string zingchart_api_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-api.min.js"; 
                            public const string zingchart_area_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-area.min.js"; 
                            public const string zingchart_area3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-area3d.min.js"; 
                            public const string zingchart_boxplot_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-boxplot.min.js"; 
                            public const string zingchart_bubble_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-bubble.min.js"; 
                            public const string zingchart_bubblepie_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-bubblepie.min.js"; 
                            public const string zingchart_calendar_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-calendar.min.js"; 
                            public const string zingchart_chord_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-chord.min.js"; 
                            public const string zingchart_core_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-core.min.js"; 
                            public const string zingchart_csv_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-csv.min.js"; 
                            public const string zingchart_debug_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-debug.min.js"; 
                            public const string zingchart_dragging_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-dragging.min.js"; 
                            public const string zingchart_errorbars_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-errorbars.min.js"; 
                            public const string zingchart_export_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-export.min.js"; 
                            public const string zingchart_gauge_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-gauge.min.js"; 
                            public const string zingchart_grid_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-grid.min.js"; 
                            public const string zingchart_guide_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-guide.min.js"; 
                            public const string zingchart_hbar_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hbar.min.js"; 
                            public const string zingchart_hbar3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hbar3d.min.js"; 
                            public const string zingchart_hbubble_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hbubble.min.js"; 
                            public const string zingchart_hbullet_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hbullet.min.js"; 
                            public const string zingchart_hfunnel_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hfunnel.min.js"; 
                            public const string zingchart_history_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-history.min.js"; 
                            public const string zingchart_hscatter_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-hscatter.min.js"; 
                            public const string zingchart_legend_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-legend.min.js"; 
                            public const string zingchart_line_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-line.min.js"; 
                            public const string zingchart_line3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-line3d.min.js"; 
                            public const string zingchart_maps_afg_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-afg.min.js"; 
                            public const string zingchart_maps_ago_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ago.min.js"; 
                            public const string zingchart_maps_alb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-alb.min.js"; 
                            public const string zingchart_maps_and_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-and.min.js"; 
                            public const string zingchart_maps_are_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-are.min.js"; 
                            public const string zingchart_maps_arg_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-arg.min.js"; 
                            public const string zingchart_maps_arm_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-arm.min.js"; 
                            public const string zingchart_maps_aus_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-aus.min.js"; 
                            public const string zingchart_maps_aut_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-aut.min.js"; 
                            public const string zingchart_maps_aze_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-aze.min.js"; 
                            public const string zingchart_maps_bdi_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bdi.min.js"; 
                            public const string zingchart_maps_bel_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bel.min.js"; 
                            public const string zingchart_maps_ben_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ben.min.js"; 
                            public const string zingchart_maps_bfa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bfa.min.js"; 
                            public const string zingchart_maps_bgr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bgr.min.js"; 
                            public const string zingchart_maps_bih_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bih.min.js"; 
                            public const string zingchart_maps_blr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-blr.min.js"; 
                            public const string zingchart_maps_bol_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bol.min.js"; 
                            public const string zingchart_maps_bra_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bra.min.js"; 
                            public const string zingchart_maps_brn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-brn.min.js"; 
                            public const string zingchart_maps_btn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-btn.min.js"; 
                            public const string zingchart_maps_bwa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-bwa.min.js"; 
                            public const string zingchart_maps_caf_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-caf.min.js"; 
                            public const string zingchart_maps_can_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-can.min.js"; 
                            public const string zingchart_maps_che_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-che.min.js"; 
                            public const string zingchart_maps_chl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-chl.min.js"; 
                            public const string zingchart_maps_chn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-chn.min.js"; 
                            public const string zingchart_maps_civ_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-civ.min.js"; 
                            public const string zingchart_maps_cmr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cmr.min.js"; 
                            public const string zingchart_maps_cod_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cod.min.js"; 
                            public const string zingchart_maps_cog_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cog.min.js"; 
                            public const string zingchart_maps_col_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-col.min.js"; 
                            public const string zingchart_maps_cri_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cri.min.js"; 
                            public const string zingchart_maps_cub_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cub.min.js"; 
                            public const string zingchart_maps_cyp_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cyp.min.js"; 
                            public const string zingchart_maps_cze_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-cze.min.js"; 
                            public const string zingchart_maps_deu_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-deu.min.js"; 
                            public const string zingchart_maps_dnk_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-dnk.min.js"; 
                            public const string zingchart_maps_ecu_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ecu.min.js"; 
                            public const string zingchart_maps_egy_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-egy.min.js"; 
                            public const string zingchart_maps_esp_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-esp.min.js"; 
                            public const string zingchart_maps_espL2_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-espL2.min.js"; 
                            public const string zingchart_maps_est_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-est.min.js"; 
                            public const string zingchart_maps_eth_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-eth.min.js"; 
                            public const string zingchart_maps_fin_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-fin.min.js"; 
                            public const string zingchart_maps_fra_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-fra.min.js"; 
                            public const string zingchart_maps_fraL2_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-fraL2.min.js"; 
                            public const string zingchart_maps_gab_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gab.min.js"; 
                            public const string zingchart_maps_gbr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gbr.min.js"; 
                            public const string zingchart_maps_gbrL2_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gbrL2.min.js"; 
                            public const string zingchart_maps_geojson_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-geojson.min.js"; 
                            public const string zingchart_maps_gha_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gha.min.js"; 
                            public const string zingchart_maps_gmb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gmb.min.js"; 
                            public const string zingchart_maps_gnb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gnb.min.js"; 
                            public const string zingchart_maps_grc_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-grc.min.js"; 
                            public const string zingchart_maps_gtm_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-gtm.min.js"; 
                            public const string zingchart_maps_guf_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-guf.min.js"; 
                            public const string zingchart_maps_guy_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-guy.min.js"; 
                            public const string zingchart_maps_hrv_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-hrv.min.js"; 
                            public const string zingchart_maps_hun_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-hun.min.js"; 
                            public const string zingchart_maps_ind_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ind.min.js"; 
                            public const string zingchart_maps_irl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-irl.min.js"; 
                            public const string zingchart_maps_irn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-irn.min.js"; 
                            public const string zingchart_maps_isl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-isl.min.js"; 
                            public const string zingchart_maps_isr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-isr.min.js"; 
                            public const string zingchart_maps_ita_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ita.min.js"; 
                            public const string zingchart_maps_jpn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-jpn.min.js"; 
                            public const string zingchart_maps_kaz_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-kaz.min.js"; 
                            public const string zingchart_maps_ken_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ken.min.js"; 
                            public const string zingchart_maps_kor_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-kor.min.js"; 
                            public const string zingchart_maps_kwt_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-kwt.min.js"; 
                            public const string zingchart_maps_lao_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-lao.min.js"; 
                            public const string zingchart_maps_lbr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-lbr.min.js"; 
                            public const string zingchart_maps_lie_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-lie.min.js"; 
                            public const string zingchart_maps_ltu_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ltu.min.js"; 
                            public const string zingchart_maps_lux_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-lux.min.js"; 
                            public const string zingchart_maps_lva_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-lva.min.js"; 
                            public const string zingchart_maps_mda_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-mda.min.js"; 
                            public const string zingchart_maps_mex_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-mex.min.js"; 
                            public const string zingchart_maps_mkd_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-mkd.min.js"; 
                            public const string zingchart_maps_mne_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-mne.min.js"; 
                            public const string zingchart_maps_moz_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-moz.min.js"; 
                            public const string zingchart_maps_nam_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-nam.min.js"; 
                            public const string zingchart_maps_ncl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ncl.min.js"; 
                            public const string zingchart_maps_nga_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-nga.min.js"; 
                            public const string zingchart_maps_nld_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-nld.min.js"; 
                            public const string zingchart_maps_nor_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-nor.min.js"; 
                            public const string zingchart_maps_nzl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-nzl.min.js"; 
                            public const string zingchart_maps_omn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-omn.min.js"; 
                            public const string zingchart_maps_pak_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-pak.min.js"; 
                            public const string zingchart_maps_pan_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-pan.min.js"; 
                            public const string zingchart_maps_per_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-per.min.js"; 
                            public const string zingchart_maps_phl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-phl.min.js"; 
                            public const string zingchart_maps_png_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-png.min.js"; 
                            public const string zingchart_maps_pol_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-pol.min.js"; 
                            public const string zingchart_maps_prt_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-prt.min.js"; 
                            public const string zingchart_maps_qat_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-qat.min.js"; 
                            public const string zingchart_maps_rou_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-rou.min.js"; 
                            public const string zingchart_maps_rus_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-rus.min.js"; 
                            public const string zingchart_maps_rwa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-rwa.min.js"; 
                            public const string zingchart_maps_sen_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-sen.min.js"; 
                            public const string zingchart_maps_slv_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-slv.min.js"; 
                            public const string zingchart_maps_srb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-srb.min.js"; 
                            public const string zingchart_maps_sur_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-sur.min.js"; 
                            public const string zingchart_maps_svk_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-svk.min.js"; 
                            public const string zingchart_maps_svn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-svn.min.js"; 
                            public const string zingchart_maps_swe_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-swe.min.js"; 
                            public const string zingchart_maps_tha_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-tha.min.js"; 
                            public const string zingchart_maps_tjk_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-tjk.min.js"; 
                            public const string zingchart_maps_topojson_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-topojson.min.js"; 
                            public const string zingchart_maps_tun_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-tun.min.js"; 
                            public const string zingchart_maps_tur_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-tur.min.js"; 
                            public const string zingchart_maps_twn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-twn.min.js"; 
                            public const string zingchart_maps_uga_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-uga.min.js"; 
                            public const string zingchart_maps_ukr_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ukr.min.js"; 
                            public const string zingchart_maps_ury_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ury.min.js"; 
                            public const string zingchart_maps_usa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa.min.js"; 
                            public const string zingchart_maps_usa_ak_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ak.min.js"; 
                            public const string zingchart_maps_usa_al_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_al.min.js"; 
                            public const string zingchart_maps_usa_ar_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ar.min.js"; 
                            public const string zingchart_maps_usa_az_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_az.min.js"; 
                            public const string zingchart_maps_usa_ca_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ca.min.js"; 
                            public const string zingchart_maps_usa_co_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_co.min.js"; 
                            public const string zingchart_maps_usa_ct_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ct.min.js"; 
                            public const string zingchart_maps_usa_dc_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_dc.min.js"; 
                            public const string zingchart_maps_usa_de_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_de.min.js"; 
                            public const string zingchart_maps_usa_fl_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_fl.min.js"; 
                            public const string zingchart_maps_usa_ga_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ga.min.js"; 
                            public const string zingchart_maps_usa_hi_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_hi.min.js"; 
                            public const string zingchart_maps_usa_ia_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ia.min.js"; 
                            public const string zingchart_maps_usa_id_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_id.min.js"; 
                            public const string zingchart_maps_usa_il_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_il.min.js"; 
                            public const string zingchart_maps_usa_in_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_in.min.js"; 
                            public const string zingchart_maps_usa_ks_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ks.min.js"; 
                            public const string zingchart_maps_usa_ky_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ky.min.js"; 
                            public const string zingchart_maps_usa_la_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_la.min.js"; 
                            public const string zingchart_maps_usa_ma_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ma.min.js"; 
                            public const string zingchart_maps_usa_md_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_md.min.js"; 
                            public const string zingchart_maps_usa_me_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_me.min.js"; 
                            public const string zingchart_maps_usa_mi_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_mi.min.js"; 
                            public const string zingchart_maps_usa_mn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_mn.min.js"; 
                            public const string zingchart_maps_usa_mo_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_mo.min.js"; 
                            public const string zingchart_maps_usa_ms_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ms.min.js"; 
                            public const string zingchart_maps_usa_mt_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_mt.min.js"; 
                            public const string zingchart_maps_usa_nc_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nc.min.js"; 
                            public const string zingchart_maps_usa_nd_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nd.min.js"; 
                            public const string zingchart_maps_usa_ne_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ne.min.js"; 
                            public const string zingchart_maps_usa_nh_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nh.min.js"; 
                            public const string zingchart_maps_usa_nj_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nj.min.js"; 
                            public const string zingchart_maps_usa_nm_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nm.min.js"; 
                            public const string zingchart_maps_usa_nv_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_nv.min.js"; 
                            public const string zingchart_maps_usa_ny_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ny.min.js"; 
                            public const string zingchart_maps_usa_oh_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_oh.min.js"; 
                            public const string zingchart_maps_usa_ok_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ok.min.js"; 
                            public const string zingchart_maps_usa_or_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_or.min.js"; 
                            public const string zingchart_maps_usa_pa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_pa.min.js"; 
                            public const string zingchart_maps_usa_ri_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ri.min.js"; 
                            public const string zingchart_maps_usa_sc_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_sc.min.js"; 
                            public const string zingchart_maps_usa_sd_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_sd.min.js"; 
                            public const string zingchart_maps_usa_tn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_tn.min.js"; 
                            public const string zingchart_maps_usa_tx_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_tx.min.js"; 
                            public const string zingchart_maps_usa_ut_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_ut.min.js"; 
                            public const string zingchart_maps_usa_va_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_va.min.js"; 
                            public const string zingchart_maps_usa_vt_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_vt.min.js"; 
                            public const string zingchart_maps_usa_wa_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_wa.min.js"; 
                            public const string zingchart_maps_usa_wi_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_wi.min.js"; 
                            public const string zingchart_maps_usa_wv_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_wv.min.js"; 
                            public const string zingchart_maps_usa_wy_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-usa_wy.min.js"; 
                            public const string zingchart_maps_uzb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-uzb.min.js"; 
                            public const string zingchart_maps_ven_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-ven.min.js"; 
                            public const string zingchart_maps_vnm_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-vnm.min.js"; 
                            public const string zingchart_maps_world_continents_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-world-continents.min.js"; 
                            public const string zingchart_maps_world_countries_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-world-countries.min.js"; 
                            public const string zingchart_maps_yem_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-yem.min.js"; 
                            public const string zingchart_maps_zaf_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-zaf.min.js"; 
                            public const string zingchart_maps_zmb_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-zmb.min.js"; 
                            public const string zingchart_maps_zwe_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps-zwe.min.js"; 
                            public const string zingchart_maps_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-maps.min.js"; 
                            public const string zingchart_navpie_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-navpie.min.js"; 
                            public const string zingchart_nestedpie_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-nestedpie.min.js"; 
                            public const string zingchart_objects_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-objects.min.js"; 
                            public const string zingchart_pareto_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-pareto.min.js"; 
                            public const string zingchart_patterns_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-patterns.min.js"; 
                            public const string zingchart_piano_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-piano.min.js"; 
                            public const string zingchart_pie_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-pie.min.js"; 
                            public const string zingchart_pie3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-pie3d.min.js"; 
                            public const string zingchart_populationpyramid_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-populationpyramid.min.js"; 
                            public const string zingchart_preview_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-preview.min.js"; 
                            public const string zingchart_r_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-r.min.js"; 
                            public const string zingchart_radar_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-radar.min.js"; 
                            public const string zingchart_range_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-range.min.js"; 
                            public const string zingchart_rankflow_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-rankflow.min.js"; 
                            public const string zingchart_refresh_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-refresh.min.js"; 
                            public const string zingchart_scalemarkers_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-scalemarkers.min.js"; 
                            public const string zingchart_scatter_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-scatter.min.js"; 
                            public const string zingchart_scroll_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-scroll.min.js"; 
                            public const string zingchart_selection_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-selection.min.js"; 
                            public const string zingchart_stock_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-stock.min.js"; 
                            public const string zingchart_toolbar3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-toolbar3d.min.js"; 
                            public const string zingchart_tooltip_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-tooltip.min.js"; 
                            public const string zingchart_treemap_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-treemap.min.js"; 
                            public const string zingchart_varea_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-varea.min.js"; 
                            public const string zingchart_vbar_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-vbar.min.js"; 
                            public const string zingchart_vbar3d_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-vbar3d.min.js"; 
                            public const string zingchart_vbullet_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-vbullet.min.js"; 
                            public const string zingchart_venn_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-venn.min.js"; 
                            public const string zingchart_vfunnel_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-vfunnel.min.js"; 
                            public const string zingchart_vline_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-vline.min.js"; 
                            public const string zingchart_waterfall_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-waterfall.min.js"; 
                            public const string zingchart_wordcloud_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-wordcloud.min.js"; 
                            public const string zingchart_xy_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-xy.min.js"; 
                            public const string zingchart_yx_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-yx.min.js"; 
                            public const string zingchart_zoom_min_js = "~/Scripts/vendors/zingchart/modules/zingchart-zoom.min.js"; 
                        }
                    }
                    public static class Assets
                    {
                        public const string zingchart_min_js = "~/Scripts/vendors/zingchart/zingchart.min.js"; 
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_ui_min_js = "~/Scripts/jquery-ui.min.js"; 
                public const string jquery_jqGrid_min_js = "~/Scripts/jquery.jqGrid.min.js"; 
                public const string jquery_signalR_2_2_0_js = "~/Scripts/jquery.signalR-2.2.0.js"; 
                public const string jquery_signalR_2_2_0_min_js = "~/Scripts/jquery.signalR-2.2.0.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string knockout_3_4_0_js = "~/Scripts/knockout-3.4.0.js"; 
                public const string main_js = "~/Scripts/main.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class rickshaw 
            {
                public static class Assets
                {
                    public const string detail_css = "~/Content/rickshaw/detail.css";
                    public const string graph_css = "~/Content/rickshaw/graph.css";
                    public const string lines_css = "~/Content/rickshaw/lines.css";
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string chart_css = "~/Content/chart.css";
                public const string jquery_ui_css = "~/Content/jquery-ui.css";
                public const string Site_css = "~/Content/Site.css";
                public const string ui_jqgrid_css = "~/Content/ui.jqgrid.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


